### ISSUE TITLE
How to change postgresql db port?

### ISSUE THREAD

**Issue by Undeadlol1** [yhnavein/express-starter#7]
Well, first of all let me thank you for the work you done on this starter kit.
As front-end developer coming to back-end, the user management seemed like too complicated thing: user creation, login through FB, change password, verify by email. All this things are very difficult to get your head around.

I have a problem starting application.

`Unhandled rejection SequelizeConnectionRefusedError: connect ECONNREFUSED 127.0.0.1:5432`

This means that there is no database on this port. Problem is i cannot create db with this port config. And there seems to be nothing blocking port :5432, i checked as hard as i could.

How can i change it to :5433 or something else?

**Comment by ghost** [comment]
http://sequelize.readthedocs.io/en/latest/api/sequelize/

**Comment by Undeadlol1** [comment]
well this is not helping at all

**Comment by yhnavein** [comment]
Hi, @Undeadlol1 

If you don't have access to the Postgres on this port, then changing it won't necessarily help as the problem may be present on the new port as well.
What system do you use for development?
If it's Linux, then you may need to edit `pg_hba.conf` file located in `/etc/postgresql/VERSION/main/pg_hba.conf` and enable login/password access.

More info here: http://stackoverflow.com/questions/4328679/how-to-configure-postgresql-so-it-accepts-loginpassword-auth

Please let me know if you have any more details about your particular issue.

**Comment by Undeadlol1** [comment]
@yhnavein Sorry for not responding.
No matter what i did postgress didn't worked for me. I moved to rethinkdb.
Thank you for your time, and sorry for wasting it

**Comment by yhnavein** [comment]
Lol
